import json
from datetime import datetime, timedelta
from decimal import Decimal
from typing import Any

from cryptospot.db import execute, fetch_all, fetch_one, get_connection
from cryptospot.capital_allocator import CapitalAllocator
from cryptospot.health import write_health_log
from cryptospot.logger import get_logger
from cryptospot.portfolio_gate import PortfolioGate
from cryptospot.settings import get_setting

SERVICE_NAME = "trade_plan_generator"
logger = get_logger(__name__)

DEFAULTS = {
    "scan.create_trade_plans": True,
    "scan.max_final_candidates": 10,
    "trade_plan.default_valid_hours": 6,
    "trade_plan.breakout_entry_buffer_percent": 0.2,
    "trade_plan.pullback_entry_percent": 1.5,
    "trade_plan.default_tp1_percent": 5.0,
    "trade_plan.default_tp2_percent": 10.0,
    "trade_plan.default_sl_percent": -4.0,
}

NOTES = "Generated by scan-based trade plan generator. Simulation only. No real order placed."
BREAKOUT_REASON = "Breakout plan created from selected scan result. Entry triggers above latest reference price with configured breakout buffer."
PULLBACK_REASON = "Pullback plan created because candidate appears extended or near 24h high. Entry triggers on configured pullback from reference price."


def json_default(value: Any):
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%d %H:%M:%S")
    return str(value)


def safe_float(value, default=None):
    if value is None or value == "":
        return default
    try:
        return float(str(value).replace(",", "").strip())
    except (TypeError, ValueError):
        return default


class TradePlanGenerator:
    def run_for_scan_run(self, scan_run_id: int, limit: int = None) -> dict:
        summary = {
            "scan_run_id": scan_run_id,
            "enabled": True,
            "eligible_candidates": 0,
            "plans_created": 0,
            "plans_updated": 0,
            "linked": 0,
            "breakout_plans": 0,
            "pullback_plans": 0,
            "skipped": 0,
            "errors": [],
            "portfolio_enabled": True,
            "portfolio_approved": 0,
            "portfolio_rejected": 0,
            "portfolio_rejection_reasons": {},
            "capital_allocated_total": 0.0,
            "capital_reserved_total": 0.0,
            "capital_reservations_created": 0,
            "allocation_rejected": 0,
            "allocation_rejection_reasons": {},
        }
        try:
            if not self._setting_bool("scan.create_trade_plans", DEFAULTS["scan.create_trade_plans"]):
                summary["enabled"] = False
                summary["skipped"] = 1
                summary["errors"].append("scan.create_trade_plans disabled")
                self._write_health("ok", f"scan_run_id={scan_run_id}, trade plan generation disabled", summary)
                return summary

            scan_run = fetch_one("SELECT id, raw_payload FROM scan_runs WHERE id = %s LIMIT 1", (scan_run_id,))
            if not scan_run:
                summary["errors"].append(f"scan_run_id={scan_run_id} not found")
                self._write_health("error", f"scan_run_id={scan_run_id} not found", summary)
                return summary

            columns = self._load_table_columns("trade_plans")
            if not columns:
                raise RuntimeError("trade_plans table is missing or has no readable columns")

            rows = self._load_eligible_rows(scan_run_id)
            summary["eligible_candidates"] = len(rows)
            if limit is None:
                limit = self._setting_int("scan.max_final_candidates", DEFAULTS["scan.max_final_candidates"])
            if limit is not None:
                rows = rows[: max(int(limit), 0)]

            settings = self._load_plan_settings()
            portfolio_gate = PortfolioGate(settings_reader=get_setting)
            capital_allocator = CapitalAllocator(settings_reader=get_setting)
            portfolio_state = portfolio_gate.get_portfolio_state()
            summary["portfolio_enabled"] = bool(portfolio_state.get("settings", {}).get("enabled", True))
            for row in rows:
                symbol = row.get("coindcx_symbol") or row.get("scan_result_id")
                try:
                    reference_price = safe_float(row.get("last_price"), safe_float(row.get("watchlist_last_price")))
                    if reference_price is None or reference_price <= 0:
                        raise ValueError("missing_reference_price")

                    primary_plan_id = None
                    for plan in self._plans_for_row(row, reference_price, settings):
                        gate_result = portfolio_gate.evaluate_candidate(self._candidate_for_gate(row, plan))
                        plan = self._apply_portfolio_gate(plan, gate_result)
                        plan_id, action = self._upsert_plan(row, plan, columns)
                        if action == "created":
                            summary["plans_created"] += 1
                        else:
                            summary["plans_updated"] += 1

                        if gate_result.get("approved"):
                            allocation = capital_allocator.allocate_for_candidate(
                                self._candidate_for_gate(row, plan),
                                self._portfolio_account(gate_result.get("portfolio_account_id")),
                            )
                            if allocation.get("approved"):
                                reservation = capital_allocator.reserve_for_trade_plan(plan_id, allocation)
                                summary["portfolio_approved"] += 1
                                summary["capital_allocated_total"] += float(allocation.get("allocated_capital") or 0)
                                if reservation.get("reserved"):
                                    summary["capital_reserved_total"] += float(allocation.get("allocated_capital") or 0)
                                if reservation.get("created_transaction"):
                                    summary["capital_reservations_created"] += 1
                                if plan["entry_strategy"] == "breakout":
                                    summary["breakout_plans"] += 1
                                    primary_plan_id = plan_id
                                elif plan["entry_strategy"] == "pullback":
                                    summary["pullback_plans"] += 1
                            else:
                                summary["allocation_rejected"] += 1
                                summary["portfolio_rejected"] += 1
                                reason = allocation.get("reason") or "portfolio_rejected_insufficient_cash_after_reserve"
                                summary["allocation_rejection_reasons"][reason] = summary["allocation_rejection_reasons"].get(reason, 0) + 1
                                summary["portfolio_rejection_reasons"][reason] = summary["portfolio_rejection_reasons"].get(reason, 0) + 1
                                self._mark_allocation_rejected(plan_id, allocation, columns)
                        else:
                            summary["portfolio_rejected"] += 1
                            reason = gate_result.get("reason") or "portfolio_rejected_unknown_error"
                            summary["portfolio_rejection_reasons"][reason] = summary["portfolio_rejection_reasons"].get(reason, 0) + 1
                    if primary_plan_id:
                        self._link_scan_result(row["scan_result_id"], primary_plan_id)
                        summary["linked"] += 1
                except Exception as exc:
                    summary["skipped"] += 1
                    summary["errors"].append(f"{symbol}: {exc}")
                    logger.exception("Trade plan generation failed for %s", symbol)

            self._update_scan_run(scan_run_id, scan_run, summary)
            status = "warning" if summary["errors"] or summary["skipped"] else "ok"
            message = f"scan_run_id={scan_run_id}, plans_created={summary['plans_created']}, plans_updated={summary['plans_updated']}, linked={summary['linked']}"
            if status == "warning":
                message += f", skipped={summary['skipped']}, errors={len(summary['errors'])}"
            self._write_health(status, message, summary)
            return summary
        except Exception as exc:
            summary["errors"].append(str(exc))
            self._write_health("error", str(exc), summary)
            return summary

    def _load_eligible_rows(self, scan_run_id: int) -> list[dict]:
        return fetch_all("""
            SELECT sr.id AS scan_result_id, sr.scan_run_id, sr.spot_symbol_id, sr.scanner_metric_id,
                   sr.candidate_watchlist_id, sr.trade_plan_id, sr.coindcx_symbol, sr.api_pair,
                   sr.base_asset, sr.quote_asset, sr.last_price, sr.change_5m_percent,
                   sr.change_15m_percent, sr.change_1h_percent, sr.change_4h_percent,
                   sr.change_24h_percent, sr.volume_spike_15m, sr.volume_spike_1h,
                   sr.quote_volume_24h, sr.spread_percent, sr.orderbook_depth_usdt,
                   sr.slippage_estimate_percent, sr.distance_from_24h_high_percent,
                   sr.candle_close_strength, sr.upper_wick_percent, sr.lower_wick_percent,
                   sr.relative_strength_vs_btc, sr.overextension_risk, sr.risk_penalty,
                   sr.final_score, sr.score_label, sr.score_breakdown, sr.score_passed,
                   sr.selected_for_watchlist, sr.selection_type, sr.selection_rank, sr.selection_reason,
                   cw.id AS watchlist_id, cw.status AS watchlist_status, cw.last_price AS watchlist_last_price
            FROM scan_results sr
            JOIN candidate_watchlists cw ON cw.id = sr.candidate_watchlist_id
            WHERE sr.scan_run_id = %s AND sr.status = 'scored' AND sr.selected_for_watchlist = 1
              AND sr.candidate_created = 1 AND sr.candidate_watchlist_id IS NOT NULL
              AND sr.spot_symbol_id IS NOT NULL AND sr.final_score IS NOT NULL
              AND cw.status IN ('active', 'refreshed') AND cw.scan_run_id = sr.scan_run_id
            ORDER BY sr.selection_rank ASC, sr.final_score DESC, sr.id ASC
        """, (scan_run_id,))

    def _plans_for_row(self, row, reference_price, settings):
        plans = [self._build_plan(row, reference_price, "breakout", settings)]
        if self._is_extended(row):
            plans.append(self._build_plan(row, reference_price, "pullback", settings))
        return plans

    def _build_plan(self, row, reference_price, strategy, settings):
        now = datetime.now()
        valid_from = now.strftime("%Y-%m-%d %H:%M:%S")
        expires_at = (now + timedelta(hours=settings["valid_hours"])).strftime("%Y-%m-%d %H:%M:%S")
        if strategy == "breakout":
            trigger = reference_price * (1 + settings["breakout_buffer"] / 100)
            condition = "breakout_above_trigger"
            reason = BREAKOUT_REASON
        else:
            trigger = reference_price * (1 - settings["pullback_percent"] / 100)
            condition = "pullback_to_entry"
            reason = PULLBACK_REASON
        entry = trigger
        tp1 = entry * (1 + settings["tp1_percent"] / 100)
        tp2 = entry * (1 + settings["tp2_percent"] / 100)
        sl = entry * (1 + settings["sl_percent"] / 100)
        risk_reward = abs(settings["tp2_percent"] / settings["sl_percent"]) if settings["sl_percent"] else None
        calc = {
            "reference_price": reference_price, "entry_strategy": strategy, "trigger_price": trigger,
            "entry_price": entry, "tp1_price": tp1, "tp2_price": tp2, "sl_price": sl,
            "trailing_start_price": tp2, "valid_from": valid_from, "expires_at": expires_at,
        }
        payload = self._build_raw_payload(row, calc)
        return {
            "scan_run_id": row.get("scan_run_id"), "scan_result_id": row.get("scan_result_id"),
            "candidate_watchlist_id": row.get("candidate_watchlist_id"), "spot_symbol_id": row.get("spot_symbol_id"),
            "coindcx_symbol": row.get("coindcx_symbol"), "api_pair": row.get("api_pair"),
            "base_asset": row.get("base_asset"), "quote_asset": row.get("quote_asset"),
            "plan_type": "scanner", "entry_strategy": strategy, "status": "pending",
            "score": row.get("final_score"), "score_label": row.get("score_label"),
            "reference_price": reference_price, "trigger_price": trigger, "confirmation_price": None,
            "entry_price": entry, "entry_condition": condition, "tp1_price": tp1, "tp2_price": tp2,
            "sl_price": sl, "trailing_start_price": tp2, "tp1_percent": settings["tp1_percent"],
            "tp2_percent": settings["tp2_percent"], "sl_percent": settings["sl_percent"],
            "risk_reward_ratio": risk_reward, "valid_from": valid_from, "expires_at": expires_at,
            "latest_price": reference_price, "highest_price_seen": reference_price, "lowest_price_seen": reference_price,
            "plan_reason": reason, "notes": NOTES, "raw_payload": json.dumps(payload, separators=(",", ":"), default=json_default),
        }

    def _build_raw_payload(self, row, calc, existing_payload=None):
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        history = []
        if isinstance(existing_payload, dict) and isinstance(existing_payload.get("history"), list):
            history = existing_payload["history"][-19:]
        history.append({"scan_run_id": row.get("scan_run_id"), "scan_result_id": row.get("scan_result_id"), "final_score": row.get("final_score"), "entry_strategy": calc.get("entry_strategy"), "trigger_price": calc.get("trigger_price"), "seen_at": now})
        return {
            "source": "scan_watchlist_candidate", "latest_scan_run_id": row.get("scan_run_id"),
            "latest_scan_result_id": row.get("scan_result_id"), "candidate_watchlist_id": row.get("candidate_watchlist_id"),
            "scanner_metric_id": row.get("scanner_metric_id"), "selection_type": row.get("selection_type"),
            "selection_rank": row.get("selection_rank"),
            "score": {"final_score": row.get("final_score"), "score_label": row.get("score_label"), "score_breakdown": self._loads(row.get("score_breakdown"))},
            "metrics": {"last_price": row.get("last_price"), "change_15m_percent": row.get("change_15m_percent"), "change_1h_percent": row.get("change_1h_percent"), "volume_spike_15m": row.get("volume_spike_15m"), "volume_spike_1h": row.get("volume_spike_1h"), "spread_percent": row.get("spread_percent"), "distance_from_24h_high_percent": row.get("distance_from_24h_high_percent"), "relative_strength_vs_btc": row.get("relative_strength_vs_btc"), "overextension_risk": row.get("overextension_risk")},
            "plan_calculation": calc,
            "history": history[-20:],
        }

    def _upsert_plan(self, row, plan, columns):
        existing = fetch_one("""
            SELECT id, raw_payload FROM trade_plans
            WHERE candidate_watchlist_id = %s AND scan_run_id = %s AND entry_strategy = %s AND status IN ('pending', 'watching')
            ORDER BY updated_at DESC LIMIT 1
        """, (row.get("candidate_watchlist_id"), row.get("scan_run_id"), plan.get("entry_strategy")))
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        if existing:
            payload = self._build_raw_payload(row, self._loads(plan["raw_payload"]).get("plan_calculation", {}), self._loads(existing.get("raw_payload")))
            plan["raw_payload"] = json.dumps(payload, separators=(",", ":"), default=json_default)
            values = {k: v for k, v in plan.items() if k in columns}
            values["updated_at"] = now
            values.pop("created_at", None)
            assignments = ", ".join([f"{key} = %s" for key in values])
            execute(f"UPDATE trade_plans SET {assignments} WHERE id = %s", tuple(values.values()) + (existing["id"],))
            return existing["id"], "updated"
        values = {k: v for k, v in plan.items() if k in columns}
        values["created_at"] = now
        values["updated_at"] = now
        keys = list(values.keys())
        placeholders = ", ".join(["%s"] * len(keys))
        connection = get_connection()
        cursor = None
        try:
            cursor = connection.cursor()
            cursor.execute(f"INSERT INTO trade_plans ({', '.join(keys)}) VALUES ({placeholders})", tuple(values[k] for k in keys))
            connection.commit()
            return cursor.lastrowid, "created"
        finally:
            if cursor:
                cursor.close()
            connection.close()

    def _link_scan_result(self, scan_result_id, trade_plan_id):
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return execute("UPDATE scan_results SET trade_plan_id = %s, trade_plan_created = 1, updated_at = %s WHERE id = %s", (trade_plan_id, now, scan_result_id))

    def _update_scan_run(self, scan_run_id, scan_run, summary):
        raw = self._loads(scan_run.get("raw_payload"))
        raw["trade_plans"] = {k: v for k, v in summary.items() if k != "scan_run_id"}
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return execute("UPDATE scan_runs SET trade_plans_created_count = %s, raw_payload = %s, updated_at = %s WHERE id = %s", (summary.get("linked", 0), json.dumps(raw, separators=(",", ":"), default=json_default), now, scan_run_id))

    def _is_extended(self, row):
        return (safe_float(row.get("change_15m_percent"), 0) >= 3 or safe_float(row.get("distance_from_24h_high_percent"), 999) <= 1 or safe_float(row.get("overextension_risk"), 0) >= 40)

    def _candidate_for_gate(self, row, plan):
        return {
            "coindcx_symbol": row.get("coindcx_symbol"),
            "score": row.get("final_score"),
            "final_score": row.get("final_score"),
            "score_label": row.get("score_label"),
            "selected_reason": row.get("selection_reason"),
            "selection_type": row.get("selection_type"),
            "entry_strategy": plan.get("entry_strategy"),
            "scan_result_id": row.get("scan_result_id"),
            "candidate_watchlist_id": row.get("candidate_watchlist_id"),
            "spot_symbol_id": row.get("spot_symbol_id"),
        }

    def _portfolio_account(self, account_id):
        if not account_id:
            return None
        return fetch_one("SELECT * FROM portfolio_accounts WHERE id = %s LIMIT 1", (account_id,))

    def _mark_allocation_rejected(self, plan_id, allocation, columns):
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        plan = fetch_one("SELECT raw_payload FROM trade_plans WHERE id = %s LIMIT 1", (plan_id,)) or {}
        raw_payload = self._loads(plan.get("raw_payload"))
        raw_payload["portfolio_allocation"] = allocation
        values = {
            "status": "portfolio_rejected",
            "portfolio_status": "rejected",
            "portfolio_rejection_reason": allocation.get("reason") or "portfolio_rejected_insufficient_cash_after_reserve",
            "rejection_reason": allocation.get("reason") or "portfolio_rejected_insufficient_cash_after_reserve",
            "portfolio_account_id": allocation.get("portfolio_account_id"),
            "allocated_capital": None,
            "allocation_percent": None,
            "capital_reserved_at": None,
            "portfolio_notes": json.dumps(allocation.get("details", {}), separators=(",", ":"), default=json_default),
            "raw_payload": json.dumps(raw_payload, separators=(",", ":"), default=json_default),
            "updated_at": now,
        }
        values = {key: value for key, value in values.items() if key in columns}
        assignments = ", ".join([f"{key} = %s" for key in values])
        return execute(f"UPDATE trade_plans SET {assignments} WHERE id = %s", tuple(values.values()) + (plan_id,))

    def _apply_portfolio_gate(self, plan, gate_result):
        raw_payload = self._loads(plan.get("raw_payload"))
        raw_payload["portfolio_gate"] = gate_result
        plan["raw_payload"] = json.dumps(raw_payload, separators=(",", ":"), default=json_default)
        plan["portfolio_account_id"] = gate_result.get("portfolio_account_id")
        plan["portfolio_status"] = gate_result.get("portfolio_status")
        plan["portfolio_notes"] = json.dumps(gate_result.get("details", {}), separators=(",", ":"), default=json_default)
        if gate_result.get("approved"):
            plan["portfolio_rejection_reason"] = None
            return plan
        plan["allocated_capital"] = None
        plan["allocation_percent"] = None
        plan["capital_reserved_at"] = None
        plan["status"] = "portfolio_rejected"
        plan["portfolio_rejection_reason"] = gate_result.get("reason") or "portfolio_rejected_unknown_error"
        plan["rejection_reason"] = plan["portfolio_rejection_reason"]
        return plan

    def _load_plan_settings(self):
        return {
            "valid_hours": self._setting_int("trade_plan.default_valid_hours", 6),
            "breakout_buffer": self._setting_float("trade_plan.breakout_entry_buffer_percent", 0.2),
            "pullback_percent": self._setting_float("trade_plan.pullback_entry_percent", 1.5),
            "tp1_percent": self._setting_float("trade_plan.default_tp1_percent", 5.0),
            "tp2_percent": self._setting_float("trade_plan.default_tp2_percent", 10.0),
            "sl_percent": self._setting_float("trade_plan.default_sl_percent", -4.0),
        }

    def _setting_bool(self, key, default):
        value = get_setting(key, default)
        return bool(value)

    def _setting_int(self, key, default):
        try:
            return int(get_setting(key, default))
        except (TypeError, ValueError):
            return default

    def _setting_float(self, key, default):
        try:
            return float(get_setting(key, default))
        except (TypeError, ValueError):
            return default

    def _load_table_columns(self, table):
        rows = fetch_all("SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s", (table,))
        return {row["COLUMN_NAME"] for row in rows}

    def _loads(self, value):
        if isinstance(value, dict):
            return value
        if not value:
            return {}
        try:
            return json.loads(value)
        except (TypeError, ValueError):
            return {}

    def _write_health(self, status, message, meta):
        try:
            write_health_log(SERVICE_NAME, status, message, meta)
        except Exception:
            logger.exception("Failed to write trade plan generator health log")
