@extends('layouts.app')

@section('content')
@php
    $num = fn($v) => $v === null ? '-' : number_format((float) $v);
    $pct = fn($v) => $v === null ? '-' : number_format((float) $v, 2).'%';
    $dec = fn($v) => $v === null ? '-' : number_format((float) $v, 2);
    $price = fn($v) => $v === null ? '-' : rtrim(rtrim(number_format((float) $v, 12), '0'), '.');
    $dt = fn($v) => $v ? \Illuminate\Support\Carbon::parse($v)->format('Y-m-d H:i') : '-';
    $yn = fn($v) => $v ? 'Yes' : 'No';
    $badge = function($value) { $v = strtolower((string) $value); return match (true) {
        in_array($v, ['yes','ok','success','completed','converted_to_trade','closed_tp1','closed_tp2','tp1_hit','tp2_hit','captured_trade_created'], true) => 'badge badge-green',
        in_array($v, ['warning','high','medium','pending','watching','triggered','trailing_started','trailing_updated'], true) => 'badge badge-yellow',
        in_array($v, ['error','failed','critical','closed_sl','closed_trailing','sl_hit','trailing_stop_hit','expired','cancelled','missed_completely'], true) => 'badge badge-red',
        in_array($v, ['low','no','missing','stale'], true) => 'badge badge-gray',
        default => 'badge badge-blue',
    }; };
    $pnlClass = fn($v) => (float) $v > 0 ? 'text-green' : ((float) $v < 0 ? 'text-red' : 'muted');
    $hasData = $summaryStats['scan_runs'] || $topGainers->isNotEmpty() || $missedReviewRows->isNotEmpty() || $simulatedTrades->isNotEmpty() || $tradeEvents->isNotEmpty();
@endphp

<header class="page-header page-header-actions">
    <div>
        <h1>Daily Review</h1>
        <p class="subtitle">Review one day of scanner coverage, actual gainers, missed candidates, trade plans, simulated trades, and system health.</p>
        <p class="muted small">Selected date: {{ $selectedDate }} · Current server time: {{ now()->format('Y-m-d H:i:s T') }} · Read-only review; no commands are executed.</p>
    </div>
    <div class="actions quick-actions">
        <a class="secondary-button" href="{{ route('cryptospot.dashboard') }}">Dashboard</a>
        <a class="secondary-button" href="{{ route('cryptospot.system-health.index') }}">System Health</a>
        <a class="secondary-button" href="{{ route('cryptospot.analytics.scanner-performance') }}">Scanner Performance</a>
        <a class="secondary-button" href="{{ route('cryptospot.analytics.trade-performance') }}">Trade Performance</a>
        <a class="secondary-button" href="{{ route('cryptospot.analytics.score-buckets') }}">Score Buckets</a>
        <a class="secondary-button" href="{{ route('cryptospot.analytics.setup-types') }}">Setup Types</a>
        <a class="secondary-button" href="{{ route('cryptospot.daily-gainers.index', ['date' => $selectedDate, 'quote_filter' => $quote]) }}">Daily Gainers</a>
        <a class="secondary-button" href="{{ route('cryptospot.missed-gainers.index', ['date' => $selectedDate, 'quote' => $quote]) }}">Missed Gainers</a>
        <a class="secondary-button" href="{{ route('cryptospot.simulated-trades.index') }}">Simulated Trades</a>
    </div>
</header>

<form class="filters" method="GET" action="{{ route('cryptospot.daily-review.index') }}">
    <label>Date <input type="date" name="date" value="{{ $selectedDate }}"></label>
    <label>Quote <input type="text" name="quote" value="{{ $quote }}"></label>
    <div class="actions"><button class="primary-button" type="submit">Apply</button></div>
</form>

@if (!$hasData)
<section class="card section-card"><h2>No daily review data found for this date.</h2><p class="muted">Generate the read-only analytics inputs from the CLI if needed:</p><pre>cd python
python scripts/run_daily_gainer_leaderboard_once.py --quote USDT --limit 100
python scripts/run_missed_gainer_analyzer_once.py --quote USDT --min-change 10 --limit 100</pre></section>
@endif

<section class="section-card"><h2>Daily Summary</h2><div class="grid metric-grid">
@foreach([
'Scan runs'=>'scan_runs','Successful scans'=>'successful_scans','Failed/error scans'=>'failed_scans','Actual 10%+ gainers'=>'actual_gainers','Matched in scan'=>'matched_in_scan','Selected for watchlist'=>'selected_for_watchlist','Trade plans created'=>'trade_plans_created','Simulated trades created'=>'simulated_trades_created','Open trades'=>'open_trades','Closed trades'=>'closed_trades','Today realized P&L %'=>'realized_pnl','Today unrealized P&L %'=>'unrealized_pnl','TP1 hits'=>'tp1_hits','TP2 hits'=>'tp2_hits','SL hits'=>'sl_hits','Trailing closes'=>'trailing_closes','Expired trades'=>'expired_trades','Critical/high review items'=>'critical_high_items'] as $label=>$key)
<article class="card metric-card"><span>{{ $label }}</span><strong class="{{ str_contains($key, 'pnl') ? $pnlClass($summaryStats[$key]) : '' }}">{{ str_contains($label, '%') ? $pct($summaryStats[$key]) : $num($summaryStats[$key]) }}</strong></article>
@endforeach
<article class="card metric-card"><span>Overall system health for day</span><strong><span class="{{ $badge($summaryStats['overall_health']) }}">{{ $summaryStats['overall_health'] }}</span></strong></article>
</div></section>

<section class="section-card"><h2>Scan Run Summary</h2><div class="grid metric-grid"><article class="card metric-card"><span>First scan time</span><strong>{{ $dt($scanSummary['first_scan_time']) }}</strong></article><article class="card metric-card"><span>Last scan time</span><strong>{{ $dt($scanSummary['last_scan_time']) }}</strong></article><article class="card metric-card"><span>Avg duration</span><strong>{{ $dec($scanSummary['avg_duration']) }}s</strong></article><article class="card metric-card"><span>Avg selected candidates</span><strong>{{ $dec($scanSummary['avg_selected']) }}</strong></article><article class="card metric-card"><span>Total selected candidates</span><strong>{{ $num($scanSummary['total_selected']) }}</strong></article></div><div class="card table-wrap"><table class="table scanner-table"><thead><tr><th>Scan run ID</th><th>Started at</th><th>Finished at</th><th>Status</th><th>Duration seconds</th><th>Active symbols</th><th>Ticker rows fetched</th><th>Prefilter passed</th><th>Scored</th><th>Selected</th><th>Trade plans</th><th>Error count/message</th><th>Link</th></tr></thead><tbody>@forelse($scanSummary['rows'] as $run)<tr><td>#{{ $run->id }}</td><td>{{ $dt($run->started_at) }}</td><td>{{ $dt($run->completed_at) }}</td><td><span class="{{ $badge($run->status) }}">{{ $run->status }}</span></td><td>{{ $num($run->duration_seconds) }}</td><td>{{ $num($run->total_active_symbols) }}</td><td>{{ $num($run->ticker_rows_fetched) }}</td><td>{{ $num($run->prefilter_passed_count) }}</td><td>{{ $num($run->scored_count) }}</td><td>{{ $num($run->watchlist_created_count) }}</td><td>{{ $num($run->trade_plans_created_count) }}</td><td>{{ $run->error_message ? \Illuminate\Support\Str::limit($run->error_message, 80) : '-' }}</td><td>@if(Route::has('cryptospot.scans.show'))<a href="{{ route('cryptospot.scans.show', $run) }}">Open scan</a>@else - @endif</td></tr>@empty<tr><td colspan="13" class="muted">No scan runs for this date.</td></tr>@endforelse</tbody></table></div></section>

<section class="section-card"><h2>Market Context Snapshot</h2>@if($marketContext)<div class="grid metric-grid"><article class="card metric-card"><span>BTC price</span><strong>{{ $price($marketContext->btc_price) }}</strong></article><article class="card metric-card"><span>BTC change/context</span><strong>{{ $pct($marketContext->btc_change_24h_percent) }}</strong></article><article class="card metric-card"><span>ETH price</span><strong>{{ $price($marketContext->eth_price) }}</strong></article><article class="card metric-card"><span>ETH change/context</span><strong>{{ $pct($marketContext->eth_change_24h_percent) }}</strong></article><article class="card metric-card"><span>Market regime/condition</span><strong>{{ $marketContext->market_condition ?? '-' }}</strong></article><article class="card metric-card"><span>Snapshot time</span><strong>{{ $dt($marketContext->snapshot_time) }}</strong></article></div>@else<p class="card muted">No market snapshot found for this date.</p>@endif</section>

<section class="section-card"><h2>Top Actual Daily Gainers</h2><div class="card table-wrap"><table class="table scanner-table"><thead><tr><th>Rank</th><th>Symbol</th><th>Last price</th><th>24h change %</th><th>24h quote volume</th><th>Spread %</th><th>Matched in scan</th><th>Selected</th><th>Trade plan</th><th>Sim trade</th><th>Best score</th><th>Score label</th></tr></thead><tbody>@forelse($topGainers as $row)<tr><td>#{{ $row->rank }}</td><td>{{ $row->coindcx_symbol }}</td><td>{{ $price($row->last_price) }}</td><td><span class="{{ $badge(((float)$row->change_24h_percent >= 20) ? 'critical' : 'ok') }}">{{ $pct($row->change_24h_percent) }}</span></td><td>{{ $num($row->quote_volume_24h) }}</td><td>{{ $pct($row->spread_percent) }}</td><td><span class="{{ $badge($yn($row->matched_in_scan)) }}">{{ $yn($row->matched_in_scan) }}</span></td><td><span class="{{ $badge($yn($row->selected_for_watchlist)) }}">{{ $yn($row->selected_for_watchlist) }}</span></td><td><span class="{{ $badge($yn($row->trade_plan_created)) }}">{{ $yn($row->trade_plan_created) }}</span></td><td><span class="{{ $badge($yn($row->simulated_trade_created)) }}">{{ $yn($row->simulated_trade_created) }}</span></td><td>{{ $dec($row->best_final_score) }}</td><td><span class="{{ $badge($row->best_score_label) }}">{{ $row->best_score_label ?? '-' }}</span></td></tr>@empty<tr><td colspan="12" class="muted">No daily gainer leaderboard rows for this date/quote.</td></tr>@endforelse</tbody></table></div></section>

<section class="section-card"><h2>Missed / Review Needed Gainers</h2><div class="card table-wrap"><table class="table scanner-table"><thead><tr><th>Rank</th><th>Symbol</th><th>Actual change %</th><th>Best score</th><th>Score label</th><th>Matched</th><th>Selected</th><th>Trade plan</th><th>Sim trade</th><th>Miss type</th><th>Miss reason</th><th>Severity</th><th>Action needed</th></tr></thead><tbody>@forelse($missedReviewRows as $row)<tr><td>#{{ $row->leaderboard_rank }}</td><td>{{ $row->coindcx_symbol }}</td><td>{{ $pct($row->actual_change_24h_percent) }}</td><td>{{ $dec($row->best_final_score) }}</td><td>{{ $row->best_score_label ?? '-' }}</td><td>{{ $yn($row->matched_in_scan) }}</td><td>{{ $yn($row->selected_for_watchlist) }}</td><td>{{ $yn($row->trade_plan_created) }}</td><td>{{ $yn($row->simulated_trade_created) }}</td><td><span class="{{ $badge($row->miss_type) }}">{{ $row->miss_type ?? '-' }}</span></td><td>{{ $row->miss_reason ?? '-' }}</td><td><span class="{{ $badge($row->miss_severity) }}">{{ $row->miss_severity ?? '-' }}</span></td><td>{{ $row->action_needed ?? '-' }}</td></tr>@empty<tr><td colspan="13" class="muted">No review-needed missed gainer rows for this date.</td></tr>@endforelse</tbody></table></div></section>

<section class="section-card"><h2>Selected Watchlist Candidates</h2><div class="card table-wrap"><table class="table scanner-table"><thead><tr><th>Time/scan run</th><th>Symbol</th><th>Score</th><th>Score label</th><th>Setup type</th><th>Entry strategy</th><th>Selected reason</th><th>Status</th><th>Trade plan created</th></tr></thead><tbody>@forelse($selectedCandidates as $row)<tr><td>{{ $dt($row->created_at ?? $row->evaluated_at) }} {{ $row->scan_run_id ? '/ #'.$row->scan_run_id : '' }}</td><td>{{ $row->coindcx_symbol }}</td><td>{{ $dec($row->score ?? $row->final_score) }}</td><td>{{ $row->score_label ?? '-' }}</td><td>{{ $row->setup_type ?? $row->candidate_type ?? '-' }}</td><td>{{ $row->entry_strategy ?? $row->suggested_entry_strategy ?? '-' }}</td><td>{{ \Illuminate\Support\Str::limit($row->reason ?? $row->selection_reason ?? '-', 80) }}</td><td><span class="{{ $badge($row->status ?? 'selected') }}">{{ $row->status ?? 'selected' }}</span></td><td>{{ isset($row->trade_plans_count) ? ($row->trade_plans_count > 0 ? 'Yes' : 'No') : $yn($row->trade_plan_created ?? false) }}</td></tr>@empty<tr><td colspan="9" class="muted">No selected watchlist candidates found.</td></tr>@endforelse</tbody></table></div></section>

<section class="section-card"><h2>Trade Plans Created</h2><div class="card table-wrap"><table class="table scanner-table"><thead><tr><th>Created at</th><th>Symbol</th><th>Status</th><th>Entry strategy</th><th>Planned entry</th><th>Trigger price</th><th>TP1</th><th>TP2</th><th>SL</th><th>Expires at</th><th>Converted to trade</th><th>Simulated trade link</th></tr></thead><tbody>@forelse($tradePlans as $plan)<tr><td>{{ $dt($plan->created_at) }}</td><td>{{ $plan->coindcx_symbol }}</td><td><span class="{{ $badge($plan->status) }}">{{ $plan->status }}</span></td><td>{{ $plan->entry_strategy }}</td><td>{{ $price($plan->entry_price ?? $plan->reference_price) }}</td><td>{{ $price($plan->trigger_price) }}</td><td>{{ $price($plan->tp1_price) }}</td><td>{{ $price($plan->tp2_price) }}</td><td>{{ $price($plan->sl_price) }}</td><td>{{ $dt($plan->expires_at) }}</td><td>{{ $yn($plan->simulated_trade_id || $plan->converted_at) }}</td><td>@if($plan->simulated_trade_id && Route::has('cryptospot.simulated-trades.show'))<a href="{{ route('cryptospot.simulated-trades.show', $plan->simulated_trade_id) }}">Open trade</a>@else - @endif</td></tr>@empty<tr><td colspan="12" class="muted">No trade plans created on this date.</td></tr>@endforelse</tbody></table></div></section>

<section class="section-card"><h2>Simulated Trade Outcomes</h2><div class="grid metric-grid"><article class="card metric-card"><span>Open trades</span><strong>{{ $num($summaryStats['open_trades']) }}</strong></article><article class="card metric-card"><span>Closed trades</span><strong>{{ $num($summaryStats['closed_trades']) }}</strong></article><article class="card metric-card"><span>Realized P&L</span><strong class="{{ $pnlClass($summaryStats['realized_pnl']) }}">{{ $pct($summaryStats['realized_pnl']) }}</strong></article><article class="card metric-card"><span>Unrealized P&L</span><strong class="{{ $pnlClass($summaryStats['unrealized_pnl']) }}">{{ $pct($summaryStats['unrealized_pnl']) }}</strong></article><article class="card metric-card"><span>Best trade</span><strong>{{ $simulatedTrades->sortByDesc('final_pnl_percent')->first()?->coindcx_symbol ?? '-' }}</strong></article><article class="card metric-card"><span>Worst trade</span><strong>{{ $simulatedTrades->sortBy('final_pnl_percent')->first()?->coindcx_symbol ?? '-' }}</strong></article></div><div class="card table-wrap"><table class="table scanner-table"><thead><tr><th>Symbol</th><th>Status</th><th>Strategy</th><th>Score</th><th>Score label</th><th>Entry price</th><th>Latest/close price</th><th>Current P&L %</th><th>Final P&L %</th><th>Max gain %</th><th>Max drawdown %</th><th>TP1 hit</th><th>TP2 hit</th><th>SL hit</th><th>Trailing stopped</th><th>Closed at</th><th>Close reason</th><th>Detail</th></tr></thead><tbody>@forelse($simulatedTrades as $trade)<tr><td>{{ $trade->coindcx_symbol }}</td><td><span class="{{ $badge($trade->status) }}">{{ $trade->status }}</span></td><td>{{ $trade->entry_strategy ?? '-' }}</td><td>{{ $dec($trade->score) }}</td><td>{{ $trade->score_label ?? '-' }}</td><td>{{ $price($trade->entry_price) }}</td><td>{{ $price($trade->close_price ?? $trade->latest_price) }}</td><td class="{{ $pnlClass($trade->current_pnl_percent) }}">{{ $pct($trade->current_pnl_percent) }}</td><td class="{{ $pnlClass($trade->final_pnl_percent) }}">{{ $pct($trade->final_pnl_percent) }}</td><td>{{ $pct($trade->max_gain_percent) }}</td><td>{{ $pct($trade->max_drawdown_percent) }}</td><td>{{ $yn($trade->tp1_hit_at) }}</td><td>{{ $yn($trade->tp2_hit_at) }}</td><td>{{ $yn($trade->sl_hit_at) }}</td><td>{{ $yn($trade->trailing_stopped_at) }}</td><td>{{ $dt($trade->closed_at) }}</td><td>{{ $trade->close_reason ?? $trade->exit_reason ?? '-' }}</td><td>@if(Route::has('cryptospot.simulated-trades.show'))<a href="{{ route('cryptospot.simulated-trades.show', $trade) }}">Details</a>@else - @endif</td></tr>@empty<tr><td colspan="18" class="muted">No simulated trades for this date.</td></tr>@endforelse</tbody></table></div></section>

<section class="section-card"><h2>Trade Events Timeline</h2><div class="card table-wrap"><table class="table scanner-table"><thead><tr><th>Time</th><th>Symbol</th><th>Event type</th><th>Event price</th><th>Trigger price</th><th>P&L %</th><th>Previous status</th><th>New status</th><th>Message</th></tr></thead><tbody>@forelse($tradeEvents as $event)<tr><td>{{ $dt($event->event_time) }}</td><td>{{ $event->coindcx_symbol }}</td><td><span class="{{ $badge($event->event_type) }}">{{ $event->event_type }}</span></td><td>{{ $price($event->event_price) }}</td><td>{{ $price($event->trigger_price) }}</td><td class="{{ $pnlClass($event->pnl_percent) }}">{{ $pct($event->pnl_percent) }}</td><td>{{ $event->previous_status ?? '-' }}</td><td>{{ $event->new_status ?? '-' }}</td><td>{{ \Illuminate\Support\Str::limit($event->message ?? '-', 120) }}</td></tr>@empty<tr><td colspan="9" class="muted">No trade events for this date.</td></tr>@endforelse</tbody></table></div></section>

<section class="section-card"><h2>System Health for the Day</h2><div class="card table-wrap"><table class="table"><thead><tr><th>Service</th><th>Latest status</th><th>Latest checked at</th><th>Warnings count</th><th>Errors count</th><th>Latest message</th></tr></thead><tbody>@forelse($healthSummary as $row)<tr><td>{{ $row['service'] }}</td><td><span class="{{ $badge($row['latest']?->status ?? 'missing') }}">{{ $row['latest']?->status ?? 'missing' }}</span></td><td>{{ $dt($row['latest']?->checked_at) }}</td><td>{{ $num($row['warnings']) }}</td><td>{{ $num($row['errors']) }}</td><td>{{ $row['latest']?->message ? \Illuminate\Support\Str::limit($row['latest']->message, 100) : '-' }}</td></tr>@empty<tr><td colspan="6" class="muted">No health logs for this date.</td></tr>@endforelse</tbody></table></div></section>

<section class="section-card"><h2>Daily Review Notes</h2><div class="grid">@foreach($reviewNotes as $note)<article class="card"><strong>Review note</strong><p>{{ $note }}</p></article>@endforeach</div></section>
@endsection
