@extends('layouts.app')

@php
    $num = fn ($v) => $v === null ? '-' : number_format((float) $v);
    $pct = fn ($v) => $v === null ? '-' : number_format((float) $v, 2) . '%';
    $dec = fn ($v) => $v === null ? '-' : number_format((float) $v, 2);
    $dt = fn ($v) => $v ? \Illuminate\Support\Carbon::parse($v)->format('Y-m-d H:i') : '-';
    $yn = fn ($v) => $v ? 'Yes' : 'No';
    $pnlClass = fn ($v) => (float) $v > 0 ? 'text-green' : ((float) $v < 0 ? 'text-red' : 'muted');
    $setupBadge = fn ($v) => match ((string) $v) {'breakout' => 'badge badge-blue','momentum_breakout' => 'badge badge-purple','pullback' => 'badge badge-orange','volume_breakout' => 'badge badge-green','fallback' => 'badge badge-blue','unknown' => 'badge badge-gray', default => 'badge badge-gray'};
    $strategyBadge = fn ($v) => match ((string) $v) {'breakout' => 'badge badge-blue','pullback' => 'badge badge-orange', default => 'badge badge-gray'};
    $statusBadge = fn ($v) => match ((string) $v) {'active' => 'badge badge-blue','tp1_hit' => 'badge badge-green','tp2_hit' => 'badge badge-purple','trailing_active' => 'badge badge-green','closed_sl' => 'badge badge-red','closed_trailing' => 'badge badge-green','expired' => 'badge badge-gray','cancelled','error' => 'badge badge-red', default => 'badge badge-gray'};
    $scoreLabelBadge = fn ($v) => match ((string) $v) {'strong' => 'badge badge-green','watchlist' => 'badge badge-blue','weak' => 'badge badge-gray','fallback' => 'badge badge-yellow', default => 'badge badge-gray'};
@endphp

@section('content')
<header class="page-header page-header-actions">
    <div>
        <h1>Setup-Type Analytics</h1>
        <p class="subtitle">Analyze which scanner setups, entry strategies, and candidate patterns perform best across scans, plans, simulated trades, and missed gainers.</p>
        <p class="muted small">Read-only analytics only. This page does not execute Python, call CoinDCX, change setup/scoring/scanner/trade logic, create trades, or add real trading.</p>
    </div>
    <div class="actions quick-actions">
        <a class="secondary-button" href="{{ route('cryptospot.dashboard') }}">Dashboard</a>
        <a class="secondary-button" href="{{ route('cryptospot.analytics.scanner-performance') }}">Scanner Performance</a>
        <a class="secondary-button" href="{{ route('cryptospot.analytics.trade-performance') }}">Trade Performance</a>
        <a class="secondary-button" href="{{ route('cryptospot.analytics.score-buckets') }}">Score Buckets</a>
        <a class="secondary-button" href="{{ route('cryptospot.missed-gainers.index') }}">Missed Gainers</a>
        <a class="secondary-button" href="{{ route('cryptospot.simulated-trades.index') }}">Simulated Trades</a>
    </div>
</header>

<section class="card section-card">
    <form class="filters" method="GET" action="{{ route('cryptospot.analytics.setup-types') }}">
        <label>From date<input type="date" name="from" value="{{ $filters['from'] }}"></label>
        <label>To date<input type="date" name="to" value="{{ $filters['to'] }}"></label>
        <label>Quote<input name="quote" value="{{ $filters['quote'] }}" placeholder="USDT or ALL"></label>
        <label>Setup type<input name="setup_type" value="{{ $filters['setup_type'] === 'all' ? '' : $filters['setup_type'] }}" placeholder="all, breakout, pullback"></label>
        <label>Entry strategy<select name="entry_strategy"><option value="all">All</option>@foreach(['breakout','pullback'] as $s)<option value="{{ $s }}" @selected($filters['entry_strategy']===$s)>{{ ucfirst($s) }}</option>@endforeach</select></label>
        <label>Score label<select name="score_label"><option value="all">All labels</option>@foreach(['strong','watchlist','weak','fallback'] as $l)<option value="{{ $l }}" @selected($filters['score_label']===$l)>{{ ucfirst($l) }}</option>@endforeach</select></label>
        <label>Selected<select name="selected"><option value="all">All</option><option value="yes" @selected($filters['selected']==='yes')>Yes</option><option value="no" @selected($filters['selected']==='no')>No</option></select></label>
        <label>Min actual gain %<input type="number" step="0.01" name="min_change" value="{{ $filters['min_change'] }}"></label>
        <label>Trade state<select name="trade_state"><option value="all">All</option><option value="open" @selected($filters['trade_state']==='open')>Open</option><option value="closed" @selected($filters['trade_state']==='closed')>Closed</option></select></label>
        <div class="actions"><button class="primary-button" type="submit">Apply</button><a class="secondary-button" href="{{ route('cryptospot.analytics.setup-types') }}">Reset</a></div>
    </form>
</section>

<section class="section-card"><h2>Summary Cards</h2><div class="grid metric-grid">
@foreach([
'Total scan candidates'=>$summaryStats['scan_candidates'],'Distinct setup types'=>$summaryStats['distinct_setup_types'],'Selected candidates'=>$summaryStats['selected'],'Trade plans created'=>$summaryStats['trade_plans'],'Simulated trades created'=>$summaryStats['sim_trades'],'Best setup by avg final P&L'=>($summaryStats['best_avg_final']['setup_type'] ?? '-') . ' / ' . $pct($summaryStats['best_avg_final']['avg_final'] ?? null),'Best setup by TP2 rate'=>($summaryStats['best_tp2']['setup_type'] ?? '-') . ' / ' . $pct($summaryStats['best_tp2']['tp2_rate'] ?? null),'Worst setup by SL rate'=>($summaryStats['worst_sl']['setup_type'] ?? '-') . ' / ' . $pct($summaryStats['worst_sl']['sl_rate'] ?? null),'Actual '.$summaryStats['min_change'].'%+ gainers analyzed'=>$summaryStats['actual_gainers'],'Captured-not-selected gainers'=>$summaryStats['captured_not_selected'],'Most common missed setup'=>($summaryStats['common_missed_setup']['setup_type'] ?? '-') . ' / ' . $num($summaryStats['common_missed_setup']['actual_gainers'] ?? null),'Most common trade setup'=>($summaryStats['common_trade_setup']['setup_type'] ?? '-') . ' / ' . $num($summaryStats['common_trade_setup']['trades'] ?? null)
] as $label=>$value)<article class="card metric-card"><span>{{ $label }}</span><strong>{{ is_numeric($value) ? $num($value) : $value }}</strong></article>@endforeach
</div></section>

<section class="card section-card"><h2>Setup-Type Scan Funnel</h2>@if($summaryStats['scan_candidates'] === 0)<p class="muted">No scan results found for this date range.</p>@else<div class="table-wrap"><table class="table scanner-table"><thead><tr><th>Setup type</th><th>Scan result rows</th><th>Distinct symbols</th><th>Avg score</th><th>Selected count</th><th>Selected %</th><th>Watchlist rows</th><th>Trade plans</th><th>Simulated trades</th><th>Avg actual gainer change</th><th>Notes</th></tr></thead><tbody>@foreach($setupScanFunnel as $r)<tr><td><span class="{{ $setupBadge($r['setup_type']) }}">{{ $r['setup_type'] }}</span></td><td>{{ $num($r['rows']) }}</td><td>{{ $num($r['symbols']) }}</td><td>{{ $dec($r['avg_score']) }}</td><td>{{ $num($r['selected']) }}</td><td>{{ $pct($r['selected_pct']) }}</td><td>{{ $num($r['watchlist']) }}</td><td>{{ $num($r['trade_plans']) }}</td><td>{{ $num($r['sim_trades']) }}</td><td>{{ $pct($r['avg_actual_change']) }}</td><td>{{ $r['notes'] }}</td></tr>@endforeach</tbody></table></div>@endif</section>

<section class="card section-card"><h2>Setup-Type Trade Outcomes</h2>@if($summaryStats['sim_trades'] === 0)<p class="muted">No simulated trades found yet.</p>@else<div class="table-wrap"><table class="table scanner-table"><thead><tr><th>Setup type</th><th>Trades</th><th>Open</th><th>Closed</th><th>Win rate</th><th>TP1 hit</th><th>TP1 rate</th><th>TP2 hit</th><th>TP2 rate</th><th>SL closed</th><th>SL rate</th><th>Trailing closed</th><th>Expired</th><th>Avg current P&L</th><th>Avg final P&L</th><th>Avg max gain</th><th>Avg max drawdown</th><th>Best final/max gain</th><th>Worst final/max drawdown</th></tr></thead><tbody>@foreach($setupTradeOutcomes as $r)<tr><td><span class="{{ $setupBadge($r['setup_type']) }}">{{ $r['setup_type'] }}</span></td><td>{{ $num($r['trades']) }}</td><td>{{ $num($r['open']) }}</td><td>{{ $num($r['closed']) }}</td><td>{{ $pct($r['win_rate']) }}</td><td>{{ $num($r['tp1']) }}</td><td>{{ $pct($r['tp1_rate']) }}</td><td>{{ $num($r['tp2']) }}</td><td>{{ $pct($r['tp2_rate']) }}</td><td>{{ $num($r['sl']) }}</td><td>{{ $pct($r['sl_rate']) }}</td><td>{{ $num($r['trailing_closed']) }}</td><td>{{ $num($r['expired']) }}</td><td class="{{ $pnlClass($r['avg_current']) }}">{{ $pct($r['avg_current']) }}</td><td class="{{ $pnlClass($r['avg_final']) }}">{{ $pct($r['avg_final']) }}</td><td>{{ $pct($r['avg_max_gain']) }}</td><td>{{ $pct($r['avg_drawdown']) }}</td><td>{{ $pct($r['best_final']) }}</td><td>{{ $pct($r['worst_final']) }}</td></tr>@endforeach</tbody></table></div>@endif</section>

<section class="card section-card"><h2>Setup-Type Missed Gainer Analysis</h2>@if($summaryStats['actual_gainers'] === 0)<p class="muted">No missed gainer analysis found.</p><pre>cd python
python scripts/run_daily_gainer_leaderboard_once.py --quote USDT --limit 100
python scripts/run_missed_gainer_analyzer_once.py --quote USDT --min-change 10 --limit 100</pre>@else<div class="table-wrap"><table class="table scanner-table"><thead><tr><th>Setup type</th><th>Actual gainers</th><th>Matched in scan</th><th>Selected</th><th>Trade plans</th><th>Sim trades</th><th>Missed completely</th><th>Captured not selected</th><th>Trade plan not triggered</th><th>Avg actual change</th><th>Max actual change</th><th>Avg best score</th><th>Most common miss reason</th><th>Most common action needed</th></tr></thead><tbody>@foreach($setupMissedGainers as $r)<tr><td><span class="{{ $setupBadge($r['setup_type']) }}">{{ $r['setup_type'] }}</span></td><td>{{ $num($r['actual_gainers']) }}</td><td>{{ $num($r['matched']) }}</td><td>{{ $num($r['selected']) }}</td><td>{{ $num($r['trade_plans']) }}</td><td>{{ $num($r['sim_trades']) }}</td><td>{{ $num($r['missed_completely']) }}</td><td>{{ $num($r['captured_not_selected']) }}</td><td>{{ $num($r['trade_plan_not_triggered']) }}</td><td>{{ $pct($r['avg_change']) }}</td><td>{{ $pct($r['max_change']) }}</td><td>{{ $dec($r['avg_score']) }}</td><td>{{ $r['common_reason'] ?: '-' }}</td><td>{{ $r['common_action'] ?: '-' }}</td></tr>@endforeach</tbody></table></div>@endif</section>

<section class="card section-card"><h2>Entry Strategy Comparison</h2><div class="table-wrap"><table class="table"><thead><tr><th>Entry strategy</th><th>Trade plans</th><th>Triggered plans</th><th>Simulated trades</th><th>Trigger rate</th><th>Open trades</th><th>Closed trades</th><th>Win rate</th><th>Avg final P&L</th><th>Avg max gain</th><th>Avg max drawdown</th><th>TP1 rate</th><th>TP2 rate</th><th>SL rate</th></tr></thead><tbody>@forelse($entryStrategyStats as $r)<tr><td><span class="{{ $strategyBadge($r['entry_strategy']) }}">{{ $r['entry_strategy'] }}</span></td><td>{{ $num($r['trade_plans']) }}</td><td>{{ $num($r['triggered_plans']) }}</td><td>{{ $num($r['sim_trades']) }}</td><td>{{ $pct($r['trigger_rate']) }}</td><td>{{ $num($r['open']) }}</td><td>{{ $num($r['closed']) }}</td><td>{{ $pct($r['win_rate']) }}</td><td class="{{ $pnlClass($r['avg_final']) }}">{{ $pct($r['avg_final']) }}</td><td>{{ $pct($r['avg_max_gain']) }}</td><td>{{ $pct($r['avg_drawdown']) }}</td><td>{{ $pct($r['tp1_rate']) }}</td><td>{{ $pct($r['tp2_rate']) }}</td><td>{{ $pct($r['sl_rate']) }}</td></tr>@empty<tr><td colspan="14" class="muted">No entry strategy rows found.</td></tr>@endforelse</tbody></table></div></section>

<section class="card section-card"><h2>Top Symbols by Setup Type</h2><div class="table-wrap"><table class="table"><thead><tr><th>Setup type</th><th>Symbol</th><th>Trades</th><th>Win rate</th><th>Avg final P&L</th><th>Avg max gain</th><th>Avg drawdown</th><th>Best trade</th><th>Worst trade</th></tr></thead><tbody>@forelse($topSymbolsBySetup as $r)<tr><td><span class="{{ $setupBadge($r['setup_type']) }}">{{ $r['setup_type'] }}</span></td><td>{{ $r['symbol'] }}</td><td>{{ $num($r['trades']) }}</td><td>{{ $pct($r['win_rate']) }}</td><td class="{{ $pnlClass($r['avg_final']) }}">{{ $pct($r['avg_final']) }}</td><td>{{ $pct($r['avg_max_gain']) }}</td><td>{{ $pct($r['avg_drawdown']) }}</td><td>{{ $pct($r['best_trade']) }}</td><td>{{ $pct($r['worst_trade']) }}</td></tr>@empty<tr><td colspan="9" class="muted">No simulated trades found yet.</td></tr>@endforelse</tbody></table></div></section>

<section class="card section-card"><h2>Review Candidates</h2><div class="table-wrap"><table class="table scanner-table"><thead><tr><th>Date</th><th>Rank</th><th>Symbol</th><th>Setup type</th><th>Actual change</th><th>Best score</th><th>Score label</th><th>Matched</th><th>Selected</th><th>Trade plan</th><th>Sim trade</th><th>Miss type</th><th>Miss reason</th><th>Action needed</th></tr></thead><tbody>@forelse($reviewCandidates as $r)<tr><td>{{ $r->analysis_date }}</td><td>{{ $r->leaderboard_rank ? '#'.$r->leaderboard_rank : '-' }}</td><td>{{ $r->coindcx_symbol }}</td><td><span class="{{ $setupBadge($r->setup_type) }}">{{ $r->setup_type }}</span></td><td>{{ $pct($r->actual_change_24h_percent) }}</td><td>{{ $dec($r->best_final_score) }}</td><td><span class="{{ $scoreLabelBadge($r->best_score_label) }}">{{ $r->best_score_label ?: '-' }}</span></td><td>{{ $yn($r->matched_in_scan) }}</td><td>{{ $yn($r->selected_for_watchlist) }}</td><td>{{ $yn($r->trade_plan_created) }}</td><td>{{ $yn($r->simulated_trade_created) }}</td><td>{{ $r->miss_type ?: '-' }}</td><td>{{ $r->miss_reason ?: '-' }}</td><td>{{ $r->action_needed ?: '-' }}</td></tr>@empty<tr><td colspan="14" class="muted">No missed gainer analysis found.</td></tr>@endforelse</tbody></table></div></section>

<section class="card section-card"><h2>Latest Setup Trades</h2><div class="table-wrap"><table class="table scanner-table"><thead><tr><th>Symbol</th><th>Setup type</th><th>Entry strategy</th><th>Status</th><th>Score</th><th>Score label</th><th>Current P&L</th><th>Final P&L</th><th>Max gain</th><th>Max drawdown</th><th>Entry triggered at</th><th>Closed at</th><th>Detail link</th></tr></thead><tbody>@forelse($latestSetupTrades as $t)<tr><td>{{ $t->coindcx_symbol }}</td><td><span class="{{ $setupBadge($t->setup_type) }}">{{ $t->setup_type }}</span></td><td><span class="{{ $strategyBadge($t->entry_strategy ?? '') }}">{{ $t->entry_strategy ?: '-' }}</span></td><td><span class="{{ $statusBadge($t->status) }}">{{ $t->status ?: '-' }}</span></td><td>{{ $dec($t->score) }}</td><td><span class="{{ $scoreLabelBadge($t->score_label) }}">{{ $t->score_label ?: '-' }}</span></td><td class="{{ $pnlClass($t->current_pnl_percent) }}">{{ $pct($t->current_pnl_percent) }}</td><td class="{{ $pnlClass($t->final_pnl_percent) }}">{{ $pct($t->final_pnl_percent) }}</td><td>{{ $pct($t->max_gain_percent) }}</td><td>{{ $pct($t->max_drawdown_percent) }}</td><td>{{ $dt($t->entry_triggered_at) }}</td><td>{{ $dt($t->closed_at) }}</td><td><a href="{{ route('cryptospot.simulated-trades.show', $t->id) }}">Open trade</a></td></tr>@empty<tr><td colspan="13" class="muted">No simulated trades found yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
