@extends('layouts.app')

@php
    $num = fn ($v) => $v === null ? '-' : number_format((float) $v);
    $pct = fn ($v) => $v === null ? '-' : number_format((float) $v, 2) . '%';
    $dec = fn ($v) => $v === null ? '-' : number_format((float) $v, 2);
    $price = fn ($v) => $v === null || $v === '' ? '-' : rtrim(rtrim(number_format((float) $v, 12, '.', ''), '0'), '.');
    $dt = fn ($v) => $v ? \Illuminate\Support\Carbon::parse($v)->format('Y-m-d H:i') : '-';
    $minutes = fn ($v) => $v === null ? '-' : number_format((float) $v, 1) . ' min';
    $pnlClass = fn ($v) => (float) $v > 0 ? 'text-green' : ((float) $v < 0 ? 'text-red' : 'muted');
    $badge = function ($value) {
        $value = strtolower((string) $value);
        return match ($value) {
            'active' => 'badge badge-blue', 'tp1_hit', 'closed_tp1' => 'badge badge-green', 'tp2_hit', 'closed_tp2', 'trailing_active' => 'badge badge-purple', 'closed_sl' => 'badge badge-red', 'closed_trailing' => 'badge badge-green', 'expired' => 'badge badge-gray', 'cancelled', 'error' => 'badge badge-red', 'breakout' => 'badge badge-purple', 'pullback' => 'badge badge-orange', 'strong' => 'badge badge-green', 'watchlist' => 'badge badge-blue', 'weak' => 'badge badge-gray', 'fallback' => 'badge badge-yellow', default => 'badge badge-gray',
        };
    };
@endphp

@section('content')
<header class="page-header page-header-actions">
    <div>
        <h1>Trade Performance Analytics</h1>
        <p class="subtitle">Analyze simulated trade outcomes, P&amp;L, TP/SL hits, trailing closes, strategy quality, and score-label performance.</p>
        <p class="muted small">Read-only Laravel analytics. No Python execution, CoinDCX API calls, real trading, or trade/scanner logic changes are available from this page.</p>
    </div>
    <div class="actions quick-actions">
        <a class="secondary-button" href="{{ route('cryptospot.dashboard') }}">Dashboard</a>
        <a class="secondary-button" href="{{ route('cryptospot.simulated-trades.index') }}">Simulated Trades</a>
        <a class="secondary-button" href="{{ route('cryptospot.analytics.scanner-performance') }}">Scanner Performance</a>
        <a class="secondary-button" href="{{ route('cryptospot.daily-gainers.index') }}">Daily Gainers</a>
        <a class="secondary-button" href="{{ route('cryptospot.missed-gainers.index') }}">Missed Gainers</a>
    </div>
</header>

<section class="card section-card">
    <form class="filters" method="GET" action="{{ route('cryptospot.analytics.trade-performance') }}">
        <label>From date<input type="date" name="from" value="{{ $filters['from'] }}"></label>
        <label>To date<input type="date" name="to" value="{{ $filters['to'] }}"></label>
        <label>Status<select name="status"><option value="all">All statuses</option>@foreach (['active','tp1_hit','tp2_hit','trailing_active','closed_sl','closed_trailing','closed_tp1','closed_tp2','expired','cancelled','error'] as $s)<option value="{{ $s }}" @selected($filters['status']===$s)>{{ $s }}</option>@endforeach</select></label>
        <label>Strategy<select name="entry_strategy"><option value="all">All strategies</option>@foreach (['breakout','pullback'] as $s)<option value="{{ $s }}" @selected($filters['entry_strategy']===$s)>{{ ucfirst($s) }}</option>@endforeach</select></label>
        <label>Score label<select name="score_label"><option value="all">All labels</option>@foreach (['strong','watchlist','weak','fallback'] as $s)<option value="{{ $s }}" @selected($filters['score_label']===$s)>{{ ucfirst($s) }}</option>@endforeach</select></label>
        <label>Symbol<input name="symbol" value="{{ $filters['symbol'] }}" placeholder="B-USDT"></label>
        <label>Trade state<select name="trade_state"><option value="all">Open and closed</option><option value="open" @selected($filters['trade_state']==='open')>Open</option><option value="closed" @selected($filters['trade_state']==='closed')>Closed</option></select></label>
        <label>Min score<input type="number" step="0.01" name="min_score" value="{{ $filters['min_score'] }}"></label>
        <label>Min P&amp;L %<input type="number" step="0.01" name="min_pnl" value="{{ $filters['min_pnl'] }}"></label>
        <div class="actions"><button class="primary-button" type="submit">Apply</button><a class="secondary-button" href="{{ route('cryptospot.analytics.trade-performance') }}">Reset</a></div>
    </form>
</section>

@if ($summaryStats['total'] === 0)
    <section class="card section-card"><p class="muted">No simulated trades found yet. Trigger trade plans and run breakout/pullback entry simulators.</p></section>
@endif

<section class="section-card"><h2>High-Level Summary</h2><div class="grid metric-grid">
@foreach ([
    'Total simulated trades'=>['total',false], 'Open trades'=>['open',false], 'Closed trades'=>['closed',false], 'Winning closed trades'=>['winning',false], 'Losing closed trades'=>['losing',false], 'Win rate'=>['win_rate',true], 'Open unrealized P&L'=>['open_unrealized',true], 'Closed realized P&L'=>['closed_realized',true], 'Average final P&L'=>['avg_final',true], 'Average max gain'=>['avg_max_gain',true], 'Average max drawdown'=>['avg_max_drawdown',true]
] as $label => [$key,$isPct])<article class="card metric-card"><span>{{ $label }}</span><strong class="{{ str_contains($label, 'P&L') || str_contains($label, 'drawdown') || str_contains($label, 'gain') ? $pnlClass($summaryStats[$key]) : '' }}">{{ $isPct ? $pct($summaryStats[$key]) : $num($summaryStats[$key]) }}</strong></article>@endforeach
<article class="card metric-card"><span>Best trade final / max gain</span><strong class="{{ $pnlClass($summaryStats['best']->final_pnl_percent ?? null) }}">{{ $summaryStats['best'] ? $summaryStats['best']->coindcx_symbol.' '.$pct($summaryStats['best']->final_pnl_percent).' / '.$pct($summaryStats['best']->max_gain_percent) : '-' }}</strong></article>
<article class="card metric-card"><span>Worst trade final / max drawdown</span><strong class="{{ $pnlClass($summaryStats['worst']->final_pnl_percent ?? null) }}">{{ $summaryStats['worst'] ? $summaryStats['worst']->coindcx_symbol.' '.$pct($summaryStats['worst']->final_pnl_percent).' / '.$pct($summaryStats['worst']->max_drawdown_percent) : '-' }}</strong></article>
</div></section>

<section class="card section-card"><h2>Outcome Breakdown</h2><div class="table-wrap"><table class="table"><thead><tr><th>Outcome/status</th><th>Count</th><th>% of total</th><th>Avg final P&amp;L %</th><th>Avg max gain %</th><th>Avg max drawdown %</th><th>Avg holding time</th></tr></thead><tbody>@forelse ($outcomeStats as $row)<tr><td><span class="{{ $badge($row['status']) }}">{{ $row['status'] }}</span></td><td>{{ $num($row['count']) }}</td><td>{{ $pct($row['percent']) }}</td><td class="{{ $pnlClass($row['avg_final']) }}">{{ $pct($row['avg_final']) }}</td><td class="{{ $pnlClass($row['avg_max_gain']) }}">{{ $pct($row['avg_max_gain']) }}</td><td class="{{ $pnlClass($row['avg_max_drawdown']) }}">{{ $pct($row['avg_max_drawdown']) }}</td><td>{{ $minutes($row['avg_holding']) }}</td></tr>@empty<tr><td colspan="7" class="muted">No outcomes found.</td></tr>@endforelse</tbody></table></div><h3>Event counts</h3><div class="grid metric-grid">@foreach (['ENTRY_TRIGGERED','TP1_HIT','TP2_HIT','SL_HIT','TRAILING_STARTED','TRAILING_UPDATED','TRAILING_STOP_HIT','EXPIRED'] as $event)<article class="card metric-card"><span>{{ $event }}</span><strong>{{ $num($eventStats[$event] ?? 0) }}</strong></article>@endforeach</div></section>

<section class="card section-card"><h2>Strategy Performance</h2><div class="table-wrap"><table class="table scanner-table"><thead><tr><th>Strategy</th><th>Trades</th><th>Open</th><th>Closed</th><th>Win rate</th><th>TP1 hit</th><th>TP2 hit</th><th>SL hit</th><th>Trailing closed</th><th>Expired</th><th>Avg current P&amp;L</th><th>Avg final P&amp;L</th><th>Avg max gain</th><th>Avg max drawdown</th><th>Best final</th><th>Worst final</th></tr></thead><tbody>@forelse ($strategyStats as $row)<tr><td><span class="{{ $badge($row['label']) }}">{{ $row['label'] }}</span></td><td>{{ $num($row['trades']) }}</td><td>{{ $num($row['open']) }}</td><td>{{ $num($row['closed']) }}</td><td>{{ $pct($row['win_rate']) }}</td><td>{{ $num($row['tp1']) }}</td><td>{{ $num($row['tp2']) }}</td><td>{{ $num($row['sl']) }}</td><td>{{ $num($row['trailing_closed']) }}</td><td>{{ $num($row['expired']) }}</td><td class="{{ $pnlClass($row['avg_current']) }}">{{ $pct($row['avg_current']) }}</td><td class="{{ $pnlClass($row['avg_final']) }}">{{ $pct($row['avg_final']) }}</td><td>{{ $pct($row['avg_max_gain']) }}</td><td>{{ $pct($row['avg_max_drawdown']) }}</td><td>{{ $pct($row['best_final']) }}</td><td>{{ $pct($row['worst_final']) }}</td></tr>@empty<tr><td colspan="16" class="muted">No strategy rows found.</td></tr>@endforelse</tbody></table></div></section>

<section class="card section-card"><h2>Score Label Performance</h2><div class="table-wrap"><table class="table"><thead><tr><th>Score label</th><th>Trades</th><th>Avg score</th><th>Win rate</th><th>TP1 rate</th><th>TP2 rate</th><th>SL rate</th><th>Avg final P&amp;L</th><th>Avg max gain</th><th>Avg max drawdown</th></tr></thead><tbody>@forelse ($scoreLabelStats as $row)<tr><td><span class="{{ $badge($row['label']) }}">{{ $row['label'] }}</span></td><td>{{ $num($row['trades']) }}</td><td>{{ $dec($row['avg_score']) }}</td><td>{{ $pct($row['win_rate']) }}</td><td>{{ $pct($row['trades'] ? $row['tp1'] / $row['trades'] * 100 : null) }}</td><td>{{ $pct($row['trades'] ? $row['tp2'] / $row['trades'] * 100 : null) }}</td><td>{{ $pct($row['trades'] ? $row['sl'] / $row['trades'] * 100 : null) }}</td><td class="{{ $pnlClass($row['avg_final']) }}">{{ $pct($row['avg_final']) }}</td><td>{{ $pct($row['avg_max_gain']) }}</td><td>{{ $pct($row['avg_max_drawdown']) }}</td></tr>@empty<tr><td colspan="10" class="muted">No score labels found.</td></tr>@endforelse</tbody></table></div></section>

<section class="card section-card"><h2>Score Bucket Performance</h2><div class="table-wrap"><table class="table"><thead><tr><th>Score bucket</th><th>Trades</th><th>Closed</th><th>Win rate</th><th>TP1 rate</th><th>TP2 rate</th><th>Avg final P&amp;L</th><th>Avg max gain</th><th>Avg drawdown</th></tr></thead><tbody>@foreach ($scoreBucketStats as $row)<tr><td>{{ $row['label'] }}</td><td>{{ $num($row['trades']) }}</td><td>{{ $num($row['closed']) }}</td><td>{{ $pct($row['win_rate']) }}</td><td>{{ $pct($row['tp1_rate']) }}</td><td>{{ $pct($row['tp2_rate']) }}</td><td class="{{ $pnlClass($row['avg_final']) }}">{{ $pct($row['avg_final']) }}</td><td>{{ $pct($row['avg_max_gain']) }}</td><td>{{ $pct($row['avg_max_drawdown']) }}</td></tr>@endforeach</tbody></table></div></section>

<section class="card section-card"><h2>Symbol Performance</h2><div class="table-wrap"><table class="table"><thead><tr><th>Symbol</th><th>Trades</th><th>Closed</th><th>Win rate</th><th>Avg final P&amp;L</th><th>Avg max gain</th><th>Avg drawdown</th><th>Best trade</th><th>Worst trade</th><th>Latest status</th></tr></thead><tbody>@forelse ($symbolStats as $row)<tr><td>{{ $row['symbol'] }}</td><td>{{ $num($row['trades']) }}</td><td>{{ $num($row['closed']) }}</td><td>{{ $pct($row['win_rate']) }}</td><td class="{{ $pnlClass($row['avg_final']) }}">{{ $pct($row['avg_final']) }}</td><td>{{ $pct($row['avg_max_gain']) }}</td><td>{{ $pct($row['avg_max_drawdown']) }}</td><td>{{ $pct($row['best']) }}</td><td>{{ $pct($row['worst']) }}</td><td><span class="{{ $badge($row['latest_status']) }}">{{ $row['latest_status'] }}</span></td></tr>@empty<tr><td colspan="10" class="muted">No symbol rows found.</td></tr>@endforelse</tbody></table></div></section>

<section class="card section-card"><h2>Holding Time Analysis</h2><div class="grid metric-grid"><article class="card metric-card"><span>Avg holding minutes</span><strong>{{ $minutes($durationStats['avg']) }}</strong></article><article class="card metric-card"><span>Fastest closed trade</span><strong>{{ $minutes($durationStats['fastest']) }}</strong></article><article class="card metric-card"><span>Longest closed trade</span><strong>{{ $minutes($durationStats['longest']) }}</strong></article></div><div class="table-wrap"><table class="table"><thead><tr><th>Status</th><th>Closed trades</th><th>Avg holding time</th></tr></thead><tbody>@forelse ($durationStats['by_status'] as $row)<tr><td><span class="{{ $badge($row['status']) }}">{{ $row['status'] }}</span></td><td>{{ $num($row['count']) }}</td><td>{{ $minutes($row['avg']) }}</td></tr>@empty<tr><td colspan="3" class="muted">No closed trades with holding time found.</td></tr>@endforelse</tbody></table></div></section>

@php
$openCols = ['Symbol','Status','Strategy','Score','Score label','Entry price','Latest price','Current P&L %','Max gain %','Max drawdown %','TP1','TP2','SL','Trailing SL','Expires at','Detail link'];
$closedCols = ['Symbol','Status','Strategy','Entry price','Close price','Final P&L %','Max gain %','Max drawdown %','Close reason','Closed at','Detail link'];
@endphp
<section class="card section-card"><h2>Latest Open Trades</h2><div class="table-wrap"><table class="table scanner-table"><thead><tr>@foreach($openCols as $c)<th>{{ $c }}</th>@endforeach</tr></thead><tbody>@forelse ($latestOpenTrades as $trade)<tr><td>{{ $trade->coindcx_symbol }}</td><td><span class="{{ $badge($trade->status) }}">{{ $trade->status }}</span></td><td><span class="{{ $badge($trade->entry_strategy) }}">{{ $trade->entry_strategy ?: '-' }}</span></td><td>{{ $dec($trade->score) }}</td><td><span class="{{ $badge($trade->score_label) }}">{{ $trade->score_label ?: '-' }}</span></td><td>{{ $price($trade->entry_price) }}</td><td>{{ $price($trade->latest_price) }}</td><td class="{{ $pnlClass($trade->current_pnl_percent) }}">{{ $pct($trade->current_pnl_percent) }}</td><td>{{ $pct($trade->max_gain_percent) }}</td><td>{{ $pct($trade->max_drawdown_percent) }}</td><td>{{ $price($trade->tp1_price) }}</td><td>{{ $price($trade->tp2_price) }}</td><td>{{ $price($trade->sl_price) }}</td><td>{{ $price($trade->current_trailing_sl_price) }}</td><td>{{ $dt($trade->expires_at) }}</td><td><a href="{{ route('cryptospot.simulated-trades.show', $trade->id) }}">Details</a></td></tr>@empty<tr><td colspan="16" class="muted">No open trades found.</td></tr>@endforelse</tbody></table></div></section>

<section class="card section-card"><h2>Latest Closed Trades</h2><div class="table-wrap"><table class="table"><thead><tr>@foreach($closedCols as $c)<th>{{ $c }}</th>@endforeach</tr></thead><tbody>@forelse ($latestClosedTrades as $trade)<tr><td>{{ $trade->coindcx_symbol }}</td><td><span class="{{ $badge($trade->status) }}">{{ $trade->status }}</span></td><td><span class="{{ $badge($trade->entry_strategy) }}">{{ $trade->entry_strategy ?: '-' }}</span></td><td>{{ $price($trade->entry_price) }}</td><td>{{ $price($trade->close_price) }}</td><td class="{{ $pnlClass($trade->final_pnl_percent) }}">{{ $pct($trade->final_pnl_percent) }}</td><td>{{ $pct($trade->max_gain_percent) }}</td><td>{{ $pct($trade->max_drawdown_percent) }}</td><td>{{ $trade->close_reason ?: '-' }}</td><td>{{ $dt($trade->closed_at) }}</td><td><a href="{{ route('cryptospot.simulated-trades.show', $trade->id) }}">Details</a></td></tr>@empty<tr><td colspan="11" class="muted">No closed trades found.</td></tr>@endforelse</tbody></table></div></section>

<section class="grid section-card"><article class="card"><h2>Best Trades</h2><div class="table-wrap"><table class="table"><thead><tr><th>Symbol</th><th>Strategy</th><th>Score</th><th>Status</th><th>Final P&amp;L %</th><th>Max gain %</th><th>Max drawdown %</th><th>Entry at</th><th>Closed at</th></tr></thead><tbody>@forelse($bestTrades as $trade)<tr><td>{{ $trade->coindcx_symbol }}</td><td>{{ $trade->entry_strategy ?: '-' }}</td><td>{{ $dec($trade->score) }}</td><td><span class="{{ $badge($trade->status) }}">{{ $trade->status }}</span></td><td class="{{ $pnlClass($trade->final_pnl_percent) }}">{{ $pct($trade->final_pnl_percent) }}</td><td>{{ $pct($trade->max_gain_percent) }}</td><td>{{ $pct($trade->max_drawdown_percent) }}</td><td>{{ $dt($trade->entry_triggered_at) }}</td><td>{{ $dt($trade->closed_at) }}</td></tr>@empty<tr><td colspan="9" class="muted">No best trades found.</td></tr>@endforelse</tbody></table></div></article><article class="card"><h2>Worst Trades</h2><div class="table-wrap"><table class="table"><thead><tr><th>Symbol</th><th>Strategy</th><th>Score</th><th>Status</th><th>Final P&amp;L %</th><th>Max gain %</th><th>Max drawdown %</th><th>Entry at</th><th>Closed at</th></tr></thead><tbody>@forelse($worstTrades as $trade)<tr><td>{{ $trade->coindcx_symbol }}</td><td>{{ $trade->entry_strategy ?: '-' }}</td><td>{{ $dec($trade->score) }}</td><td><span class="{{ $badge($trade->status) }}">{{ $trade->status }}</span></td><td class="{{ $pnlClass($trade->final_pnl_percent) }}">{{ $pct($trade->final_pnl_percent) }}</td><td>{{ $pct($trade->max_gain_percent) }}</td><td>{{ $pct($trade->max_drawdown_percent) }}</td><td>{{ $dt($trade->entry_triggered_at) }}</td><td>{{ $dt($trade->closed_at) }}</td></tr>@empty<tr><td colspan="9" class="muted">No worst trades found.</td></tr>@endforelse</tbody></table></div></article></section>
@endsection
